# Generated by Django 5.2.2 on 2025-06-12 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='brigade',
        ),
        migrations.AddField(
            model_name='worker',
            name='brigade',
            field=models.ManyToManyField(related_name='workers', to='core.brigade'),
        ),
        migrations.CreateModel(
            name='TimeSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hours_worked', models.PositiveSmallIntegerField(default=0)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.worker')),
            ],
            options={
                'ordering': ['date', 'worker'],
                'unique_together': {('worker', 'date')},
            },
        ),
    ]
